### ISSUE TITLE
任务启动失败！错误信息：Wrong number of fields; got 6, expected 5

### ISSUE THREAD

**Issue by yangshare** [luoce/bt-ware-datasync-datax#1]
ERROR - job_define_controller.py - startup - 173 - audit_data_age_copy 任务启动失败！错误信息：Wrong number of fields; got 6, expected 5

**Comment by luoce** [comment]
请检查任务配置json，查看进出字段数是否一致。谢谢。

**Comment by yangshare** [comment]
![image](https://user-images.githubusercontent.com/15276085/50812632-7acad200-134e-11e9-980e-0e928bf42191.png)

**Comment by luoce** [comment]
可以贴出你的完整的json配置内容，我们一起探讨

**Comment by yangshare** [comment]
JobJson配置
[job.txt](https://github.com/luoce/bt-ware-datasync-datax/files/2735366/job.txt)

**Comment by yangshare** [comment]
其实我是想用java重写一个，但是碍于年底时间太紧了，你这个算是我看过的比较完整的，所以如果你这个能弄好，我就不用重复造轮子了

**Comment by yangshare** [comment]
![image](https://user-images.githubusercontent.com/15276085/50813090-32141880-1350-11e9-8bb5-c49b8fd5959e.png)

**Comment by luoce** [comment]
这是传递到任务创建，用于作为任务维护标识的

**Comment by yangshare** [comment]
![image](https://user-images.githubusercontent.com/15276085/50813245-bf576d00-1350-11e9-86e6-3042e14beb26.png)

**Comment by yangshare** [comment]
是不是这边参数非空判断

**Comment by yangshare** [comment]
某些参数留白，然后代码里面没判断，遍历参数时异常了

**Comment by luoce** [comment]
我查看了错误，是crontab表达式错误，需要使用标准的unix crontab表达式，5位就够了，这和java的schaduler有一些区别

**Comment by luoce** [comment]
> 我查看了错误，是crontab表达式错误，需要使用标准的unix crontab表达式，5位就够了，这和java的schaduler有一些区别

你可以参考unix crontab的表达式标准，谢谢。

**Comment by yangshare** [comment]
![image](https://user-images.githubusercontent.com/15276085/50813607-ea8e8c00-1351-11e9-9019-06327885582b.png)
