### ISSUE TITLE
使用疑问

### ISSUE THREAD

**Issue by yangshare** [luoce/bt-ware-datasync-datax#2]
兄弟，貌似没有调用datax去跑job啊
![image](https://user-images.githubusercontent.com/15276085/50814975-74d8ef00-1356-11e9-97b8-8a87439c0567.png)

**Comment by yangshare** [comment]
直接用cmd跑datax迁移数据是ok的
![image](https://user-images.githubusercontent.com/15276085/50815043-b23d7c80-1356-11e9-8339-c8ab7c1307d4.png)

**Comment by yangshare** [comment]
麻烦你，有空帮忙看看，谢谢

**Comment by luoce** [comment]
每次执行后，都有日志产生，你可以看看执行记录里面的日志内容

**Comment by yangshare** [comment]
这个日志真的看不出个啥，因为这边执行了，但是并没有调用datax，所以它是没有日志可看的。
![image](https://user-images.githubusercontent.com/15276085/50817554-24b25a80-135f-11e9-9633-bcac87b86b46.png)

**Comment by yangshare** [comment]
![image](https://user-images.githubusercontent.com/15276085/50817591-4ca1be00-135f-11e9-848d-33b7986b1ba2.png)

**Comment by luoce** [comment]
请附上执行记录页面的截图，谢谢

**Comment by yangshare** [comment]
![image](https://user-images.githubusercontent.com/15276085/50819296-9fca3f80-1364-11e9-98d7-2eeff3552f9d.png)

![image](https://user-images.githubusercontent.com/15276085/50819281-96d96e00-1364-11e9-956c-3a1fe456c536.png)

**Comment by yangshare** [comment]
![image](https://user-images.githubusercontent.com/15276085/50819334-b4a6d300-1364-11e9-991b-f24ddc7fadad.png)

**Comment by luoce** [comment]
目测是python commonds模块不兼容windows的原因，我是unix开发，linux运行

**Comment by yangshare** [comment]
好的，谢谢
